<template>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>

<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&family=Libre+Caslon+Display&display=swap');
:root{--ivory:#f5f2eb;--paper:#faf8f3;--ink:#20201f;--terra:#ad3c25;--line:#d9d3c9;--serif:'Libre Caslon Display',Georgia,serif;--sans:'DM Sans',Arial,sans-serif}*{box-sizing:border-box}html{scroll-behavior:smooth;background:var(--ivory)}body{margin:0;color:var(--ink);background:var(--ivory);font:15px/1.55 var(--sans)}a{color:inherit;text-decoration:none}button{font:inherit}.shell{width:min(1180px,calc(100% - 72px));margin-inline:auto}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}:focus-visible{outline:3px solid #d6654e;outline-offset:4px}
.site-header{height:108px;background:rgba(250,248,243,.97);border-bottom:1px solid var(--line);position:relative;z-index:20}.header-inner{height:100%;display:flex;align-items:center;justify-content:space-between}.brand{display:inline-flex;align-items:center;gap:13px;text-transform:uppercase;letter-spacing:.23em;font-weight:600;font-size:16px;line-height:1.25}.brand-mark{width:49px;height:49px;fill:var(--terra);flex:none}nav{display:flex;align-items:center;gap:52px;font-size:13px;font-weight:600;text-transform:uppercase}nav a:not(.quote-button){padding:42px 0 15px;border-bottom:2px solid transparent}nav a.active{color:var(--terra);border-color:var(--terra)}.quote-button{color:#fff;background:var(--terra);padding:17px 36px;letter-spacing:.04em;transition:.2s}.quote-button:hover{background:#8e2f1d;transform:translateY(-2px)}.menu-button{display:none;background:none;border:0;padding:10px}
.hero{min-height:616px;display:grid;grid-template-columns:minmax(420px,47%) 1fr;background:var(--paper)}.hero-copy{width:min(590px,calc(100% - 70px));padding:105px 0 75px;margin-right:0}.eyebrow{margin:0 0 20px;color:var(--terra);text-transform:uppercase;letter-spacing:.09em;font-size:13px;font-weight:600}h1{margin:0;font:400 clamp(60px,6vw,86px)/.98 var(--serif);letter-spacing:-.035em}h1 span{color:var(--terra)}.short-rule{width:52px;height:2px;margin:47px 0 28px;background:var(--terra)}.hero-description{max-width:460px;margin:0;color:#393733;font-size:17px;line-height:1.6}.hero-image-wrap{min-height:616px;overflow:hidden}.hero-image-wrap img{width:100%;height:100%;object-fit:cover;display:block}
.catalog{padding:38px 0 72px}.filters{display:flex;align-items:center;gap:45px;margin-bottom:42px}.filters p{font-family:var(--serif);font-size:17px;white-space:nowrap}.filter-options{display:flex;gap:20px;width:100%}.filter-options button{flex:1;min-height:45px;border:1px solid var(--line);background:transparent;border-radius:99px;text-transform:uppercase;color:#33312e;font-size:12px;font-weight:600;cursor:pointer;transition:.2s}.filter-options button:hover{border-color:var(--terra);color:var(--terra)}.filter-options button.active{color:white;border-color:var(--terra);background:var(--terra)}.product-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:30px 24px;min-height:400px}.product-card{background:var(--paper);border:1px solid #ded8ce;box-shadow:0 5px 18px rgba(43,32,20,.035);transition:.28s}.product-card:hover,.product-card:focus-within{transform:translateY(-5px);box-shadow:0 14px 30px rgba(43,32,20,.1)}.product-image{aspect-ratio:4/3;overflow:hidden}.product-image img{width:100%;height:100%;object-fit:cover;display:block;transition:transform .5s}.product-card:hover img{transform:scale(1.025)}.product-body{padding:17px 18px 22px}.product-body h3{margin:0 0 16px;font:400 26px/1.1 var(--serif)}.finish-label{margin:0 0 10px;font-size:12px}.swatches{display:flex;gap:12px;margin-bottom:18px}.swatch{width:35px;height:35px;border-radius:50%;border:1px solid rgba(0,0,0,.08);box-shadow:inset 0 0 0 1px rgba(255,255,255,.18)}.description{min-height:47px;margin:0 0 17px;color:#3f3c38;font-size:13px;line-height:1.45}.product-body a{color:var(--terra);font-size:13px;font-weight:600}.product-body a span{display:inline-block;margin-left:9px;transition:transform .2s}.product-body a:hover span{transform:translateX(4px)}.product-list-enter-active,.product-list-leave-active{transition:all .25s ease}.product-list-enter-from,.product-list-leave-to{opacity:0;transform:translateY(12px)}
.sample-cta{color:#fff;background-color:var(--terra);background-image:linear-gradient(90deg,rgba(130,35,18,.1),transparent 60%),repeating-linear-gradient(90deg,transparent 0,transparent 93%,rgba(93,24,13,.08) 93%,rgba(93,24,13,.08) 94%)}.sample-inner{min-height:154px;display:grid;grid-template-columns:1.2fr .9fr .9fr;align-items:center;gap:52px}.sample-inner h2{margin:0;font:400 clamp(38px,4vw,50px)/1 var(--serif)}.sample-inner p{margin:0;font-size:17px}.sample-inner a{padding:18px 28px;border:2px solid white;text-transform:uppercase;text-align:center;font-weight:600;letter-spacing:.05em;transition:.2s}.sample-inner a:hover{color:var(--terra);background:#fff}.sample-inner a span{margin-left:30px;font-size:22px}
.site-footer{padding:46px 0 18px;background:var(--paper)}.footer-grid{display:grid;grid-template-columns:1.45fr .7fr .85fr 1.05fr;gap:60px;padding-bottom:42px}.footer-about .brand{margin-bottom:22px;font-size:14px}.footer-about .brand-mark{width:42px}.footer-about p{max-width:290px;margin:0;color:#494641;font-size:12px}.footer-grid h2{margin:5px 0 19px;font:600 12px/1 var(--sans);text-transform:uppercase}.footer-grid>div:not(:first-child) a,.footer-grid>div:not(:first-child) p{display:block;margin:0 0 9px;color:#4e4a45;font-size:12px}.footer-grid a:hover{color:var(--terra)}.instagram{margin-top:16px!important;color:var(--terra)!important;font-weight:600}.copyright{border-top:1px solid var(--line);padding-top:17px;margin-bottom:0;text-align:center;color:#625e58;font-size:11px}
@media(max-width:900px){.shell{width:min(100% - 40px,760px)}.site-header{height:86px}.brand{font-size:13px}.brand-mark{width:40px}nav{gap:22px;font-size:11px}.quote-button{padding:14px 18px}nav a:not(.quote-button){padding:31px 0 12px}.hero{min-height:auto;grid-template-columns:1fr}.hero-copy{width:min(100% - 40px,760px);margin:auto;padding:70px 0 58px}.hero-image-wrap{min-height:0;height:55vw;max-height:560px}.catalog{padding-top:30px}.filters{align-items:flex-start;flex-direction:column;gap:12px}.filters p{margin:0}.filter-options{overflow:auto;padding:3px 3px 8px}.filter-options button{min-width:140px;padding-inline:18px}.product-grid{grid-template-columns:repeat(2,1fr)}.sample-inner{grid-template-columns:1fr 1fr;padding-block:34px}.sample-inner a{grid-column:2;grid-row:1/span 2}.footer-grid{grid-template-columns:1.3fr 1fr 1fr}.footer-grid>div:last-child{grid-column:2/span 2}}
@media(max-width:620px){.shell{width:calc(100% - 32px)}.site-header{height:76px}.menu-button{display:flex;flex-direction:column;gap:6px}.menu-button span{width:25px;height:2px;background:var(--ink)}nav{display:none;position:absolute;top:76px;inset-inline:0;padding:25px 20px;background:var(--paper);border-bottom:1px solid var(--line);flex-direction:column;align-items:stretch;gap:0}nav.open{display:flex}nav a:not(.quote-button){padding:13px 3px;border:0}.quote-button{margin-top:14px;text-align:center}.hero-copy{width:calc(100% - 32px);padding:55px 0 45px}h1{font-size:51px}.eyebrow{margin-bottom:16px}.short-rule{margin:32px 0 23px}.hero-description{font-size:15px}.hero-image-wrap{height:72vw}.catalog{padding-bottom:48px}.filters{margin-bottom:25px}.filter-options{gap:9px}.product-grid{grid-template-columns:1fr;gap:20px}.product-body h3{font-size:25px}.description{min-height:0}.sample-inner{display:flex;flex-direction:column;align-items:flex-start;gap:18px;padding-block:38px}.sample-inner p{font-size:15px}.sample-inner a{width:100%;margin-top:5px}.footer-grid{grid-template-columns:1fr 1fr;gap:38px 25px}.footer-about{grid-column:1/-1}.footer-grid>div:last-child{grid-column:auto}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*,*::before,*::after{animation-duration:.01ms!important;transition-duration:.01ms!important}}
.line-icon{display:block;width:100%;height:100%}.promise-icon{font-size:0}.promise-icon .line-icon{width:42px;height:42px}.step-icon{font-size:0}.step-icon .line-icon{width:40px;height:40px}

/* Homepage */
.home-hero{display:grid;grid-template-columns:44.2% 55.8%;min-height:730px;background:var(--paper)}.home-hero-copy{width:min(540px,calc(100% - 68px));margin-right:0;padding:90px 0 58px}.home-hero-copy h1{font-size:82px}.home-hero-copy>p{max-width:410px;margin:0;color:#3c3935;font-size:16px}.home-hero-image{overflow:hidden}.home-hero-image img{width:100%;height:100%;display:block;object-fit:cover}.promise-row{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:55px}.promise-row>div{display:flex;flex-direction:column;gap:12px}.promise-icon{display:grid;place-items:center;width:43px;height:43px;color:var(--terra);font-size:34px}.promise-row strong{text-transform:uppercase;letter-spacing:.07em;font-size:11px;line-height:1.45}
.surface-section{padding:44px 0 62px}.surface-section header{text-align:center;margin-bottom:27px}.surface-section h2,.projects-heading h2,.process-section>h2,.home-quote h2{margin:0;font:400 44px/1.08 var(--serif)}.surface-section header p{margin:12px 0 0;color:var(--terra);text-transform:uppercase;letter-spacing:.12em;font-size:11px;font-weight:600}.surface-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:31px}.surface-card{background:var(--paper);border:1px solid #e1dcd2}.surface-card>img{width:100%;aspect-ratio:1.5;object-fit:cover;display:block}.surface-card>div{padding:19px 18px 23px}.surface-card h3{margin:0 0 8px;text-transform:uppercase;letter-spacing:.06em;font-size:17px}.surface-card p{min-height:44px;margin:0 0 16px;color:#4b4742;font-size:14px}.surface-card a{color:var(--terra);text-transform:uppercase;font-size:12px;font-weight:600}.surface-card a span{margin-left:8px}
.projects-section{padding:40px 0 38px;color:#f8f4ed;background:#191918}.projects-heading{display:flex;align-items:end;justify-content:space-between;margin-bottom:24px}.projects-heading>div>p{margin:0 0 5px;color:var(--terra);text-transform:uppercase;letter-spacing:.1em;font-size:12px;font-weight:600}.projects-heading h2{font-size:38px}.projects-heading>a{margin-bottom:7px;color:#d9573c;text-transform:uppercase;font-size:11px;font-weight:600}.projects-heading>a span{margin-left:11px}.projects-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.projects-grid img{width:100%;aspect-ratio:1.22;object-fit:cover;display:block}.projects-grid h3{margin:9px 0 0;text-transform:uppercase;font-size:12px}.projects-grid p{margin:1px 0 0;color:#ddd8d0;font-size:10px}
.process-section{padding:42px 0 52px}.process-section>h2{text-align:center;font-size:40px}.process-grid{display:grid;grid-template-columns:repeat(3,1fr);margin-top:26px}.process-grid article{position:relative;text-align:center}.process-grid article:not(:last-child)::after{content:'';position:absolute;top:32px;left:65%;width:70%;height:1px;background:#d9d1c6}.step-number{position:absolute;top:17px;left:10%;z-index:1;display:grid;place-items:center;width:35px;height:35px;border-radius:50%;color:#fff;background:var(--terra);font-weight:600}.step-icon{display:grid;place-items:center;width:66px;height:66px;margin:0 auto 15px;border-radius:50%;color:var(--terra);background:#eee8df;font-size:34px}.process-grid h3{margin:0 0 8px;text-transform:uppercase;font-size:12px}.process-grid p{margin:0;color:#4f4a44;font-size:12px}
.home-quote{color:#fff;background:var(--terra);background-image:linear-gradient(90deg,rgba(120,28,12,.12),transparent)}.home-quote>div{min-height:148px;display:flex;align-items:center;justify-content:space-between;padding-inline:24px}.home-quote h2{font-size:42px}.home-quote a{min-width:300px;padding:18px 30px;border:2px solid #fff;text-align:center;text-transform:uppercase;font-weight:600}.home-quote a span{margin-left:32px;font-size:20px}
@media(max-width:900px){.home-hero{grid-template-columns:1fr;min-height:0}.home-hero-copy{width:min(100% - 40px,760px);margin:auto;padding:70px 0 55px}.home-hero-image{height:65vw;max-height:610px}.surface-grid{grid-template-columns:repeat(2,1fr)}.surface-card:last-child{grid-column:1/-1;width:calc(50% - 16px);margin:auto}.projects-grid{grid-template-columns:repeat(2,1fr);gap:24px 14px}.home-quote>div{gap:30px}.home-quote a{min-width:250px}}
@media(max-width:620px){.home-hero-copy{width:calc(100% - 32px);padding:55px 0 42px}.home-hero-copy h1{font-size:56px}.home-hero-copy>p{font-size:14px}.promise-row{margin-top:38px}.promise-row strong{font-size:9px}.home-hero-image{height:78vw}.surface-section{padding:38px 0 45px}.surface-section h2,.process-section>h2{font-size:34px}.surface-grid{grid-template-columns:1fr}.surface-card:last-child{grid-column:auto;width:auto}.projects-heading{align-items:flex-start;gap:20px}.projects-heading h2{font-size:30px}.projects-heading>a{white-space:nowrap}.projects-grid{grid-template-columns:1fr 1fr}.process-grid{grid-template-columns:1fr;gap:32px;margin-top:32px}.process-grid article:not(:last-child)::after{display:none}.step-number{left:calc(50% - 70px)}.home-quote>div{padding-block:34px;flex-direction:column;align-items:flex-start}.home-quote h2{font-size:34px}.home-quote a{width:100%;min-width:0}}
</style>
