<script setup lang="ts">
const siteUrl='https://motionconstruction.ph'
const title='Premium Interior Finishing Materials Philippines'
const description='Motion Construction PH supplies premium wall panels, SPC flooring, outdoor cladding, mouldings, and architectural finishes across the Philippines.'
useSeoMeta({title,description,robots:'index, follow, max-image-preview:large',ogTitle:`${title} | Motion Construction PH`,ogDescription:description,ogType:'website',ogUrl:siteUrl,ogImage:`${siteUrl}/images/home-hero-v2.webp`,ogImageAlt:'Premium walnut fluted wall panels in a contemporary Philippine interior',twitterCard:'summary_large_image',twitterTitle:`${title} | Motion Construction PH`,twitterDescription:description,twitterImage:`${siteUrl}/images/home-hero-v2.webp`})
useHead({link:[{rel:'canonical',href:siteUrl}],script:[{type:'application/ld+json',innerHTML:JSON.stringify({'@context':'https://schema.org','@type':['LocalBusiness','HomeAndConstructionBusiness'],name:'Motion Construction PH',url:siteUrl,image:`${siteUrl}/images/home-hero-v2.webp`,description,telephone:'+63 917 123 4567',email:'hello@motionconstruction.ph',address:{'@type':'PostalAddress',addressLocality:'Quezon City',addressCountry:'PH'},areaServed:{'@type':'Country',name:'Philippines'},sameAs:['https://www.instagram.com/motionconstruction.ph/'],priceRange:'₱₱',knowsAbout:['WPC fluted wall panels','SPC flooring','outdoor WPC cladding','flexible wall panels','PU stone panels','PS mouldings']})}]})
const surfaces=[{title:'Fluted Wall Panels',copy:'Add texture, depth, and rhythm to any interior.',image:'/images/wpc-fluted.webp'},{title:'SPC Flooring',copy:'Waterproof. Durable. Beautiful under every step.',image:'/images/spc-flooring.webp'},{title:'Outdoor Cladding',copy:'Built to withstand the elements. Made to last.',image:'/images/outdoor-cladding.webp'}]
const projects=[{title:'Residence in Alabang',place:'Muntinlupa City',image:'/images/wpc-fluted.webp'},{title:'Office in BGC',place:'Taguig City',image:'/images/pu-stone.webp'},{title:'House in Cebu',place:'Cebu City',image:'/images/outdoor-cladding.webp'},{title:'Restaurant in Makati',place:'Makati City',image:'/images/flexible-panels.webp'}]
</script>
<template><div class="home-page"><SiteHeader/><main>
  <section class="home-hero"><div class="home-hero-copy shell"><h1>Materials<br>that move<br>spaces<span>.</span></h1><div class="short-rule"/><p>Motion Construction PH is a Philippine direct supplier of premium finishing materials for beautiful, durable spaces.</p><div class="promise-row"><div><span class="promise-icon"><LineIcon name="quality"/></span><strong>Premium<br>quality</strong></div><div><span class="promise-icon"><LineIcon name="truck"/></span><strong>Direct<br>supply</strong></div><div><span class="promise-icon"><LineIcon name="grid"/></span><strong>Built for<br>the Philippines</strong></div></div></div><div class="home-hero-image"><img :src="'/images/home-hero-v2.webp'" alt="Warm contemporary living room finished with walnut fluted wall panels" width="1408" height="1120" fetchpriority="high"></div></section>
  <section class="surface-section shell" aria-labelledby="surface-title"><header><h2 id="surface-title">Choose your surface.</h2><p>Finished in motion.</p></header><div class="surface-grid"><article v-for="surface in surfaces" :key="surface.title" class="surface-card"><img :src="surface.image" :alt="surface.title" width="900" height="675" loading="lazy"><div><h3>{{surface.title}}</h3><p>{{surface.copy}}</p><NuxtLink to="/products">Explore products <span>→</span></NuxtLink></div></article></div></section>
  <section id="projects" class="projects-section"><div class="shell"><div class="projects-heading"><div><p>Recent projects</p><h2>Real spaces. Lasting impact.</h2></div><a href="#projects-grid">View all projects <span>→</span></a></div><div id="projects-grid" class="projects-grid"><article v-for="project in projects" :key="project.title"><img :src="project.image" :alt="project.title" width="900" height="675" loading="lazy"><h3>{{project.title}}</h3><p>{{project.place}}</p></article></div></div></section>
  <section id="process" class="process-section shell" aria-labelledby="process-title"><h2 id="process-title">Simple from sample to finished space.</h2><div class="process-grid"><article><span class="step-number">1</span><span class="step-icon"><LineIcon name="samples"/></span><h3>Choose</h3><p>Explore our materials and<br>request a sample.</p></article><article><span class="step-number">2</span><span class="step-icon"><LineIcon name="plan"/></span><h3>Plan</h3><p>We help you select the right<br>fit for your space.</p></article><article><span class="step-number">3</span><span class="step-icon"><LineIcon name="build"/></span><h3>Deliver &amp; build</h3><p>We deliver directly and support<br>your build to the finish.</p></article></div></section>
  <section class="home-quote"><div class="shell"><h2>Let’s build the finish<br>you’ve been imagining.</h2><a href="https://www.instagram.com/motionconstruction.ph/" target="_blank" rel="noopener">Get a quote <span>→</span></a></div></section>
  </main><SiteFooter/></div></template>
